#include <stdio.h>

/**
 * @brief Macro for safe handling of CUDA API calls.
 * 
 * Wraps the `gpuAssert` function, automatically passing the filename and 
 * line number to simplify debugging in case of a malloc or memcpy failure on the device.
 * 
 * @param ans The return code (cudaError_t) provided by the CUDA function.
 */
#define gpuErrchk(ans) { gpuAssert((ans), __FILE__, __LINE__); }

/**
 * @brief Intercepts and analyzes CUDA error codes.
 * 
 * @param code The error code returned by the CUDA call.
 * @param file The source file where the error occurred (generated by __FILE__).
 * @param line The line number where the error occurred (generated by __LINE__).
 * @param abort If true (default), terminates program execution via exit() upon error.
 */
inline void gpuAssert(cudaError_t code, const char *file, int line, bool abort=true)
{
   if (code != cudaSuccess) 
   {
      fprintf(stderr,"GPUassert: %s %s %d\n", cudaGetErrorString(code), file, line);
      if (abort) exit(code);
   }
}