/*
 * CSVParser.h
 * 
 * This file defines the CSVParser class, which is used to read the four CSV files
 * containing the dataframes (DF1, DF2, DF3, DF4) generated by the original parser.
 * Each CSV corresponds to a normalized table of the VCF data.
 */

#ifndef CSV_PARSER_H
#define CSV_PARSER_H

#include <string>
#include <vector>
#include "VCFDataFrames.h"

/*
 * The CSVParser class opens the CSV files, reads them line by line,
 * splits each line into fields, and fills the dataframe structures.
 * The four dataframes are passed in from outside and get populated with the read data.
 */
class CSVParser
{
private:
    // Paths to the four CSV files
    std::string df1_path;   // CSV for DF1 (main variant data)
    std::string df2_path;   // CSV for DF2 (alternative alleles)
    std::string df3_path;   // CSV for DF3 (sample data)
    std::string df4_path;   // CSV for DF4 (sample × allele data)

    /*
     * Reads the DF1 CSV file and fills the given var_columns_df structure.
     * It skips the header line and processes each subsequent line,
     * populating the vectors for chromosome, position, id, ref, qual, filter,
     * and all INFO fields.
     */
    void parseDF1(var_columns_df& df1);

    /*
     * Reads the DF2 CSV file and fills the given alt_columns_df structure.
     * It stores alternative allele strings and per-allele INFO fields.
     */
    void parseDF2(alt_columns_df& df2);

    /*
     * Reads the DF3 CSV file and fills the given sample_columns_df structure.
     * It stores per‑sample fixed fields (like GT, DP, etc.) and the sample name mapping.
     */
    void parseDF3(sample_columns_df& df3);

    /*
     * Reads the DF4 CSV file and fills the given alt_format_df structure.
     * It stores the three‑way combination of variant, sample, and allele,
     * along with the corresponding per‑sample per‑allele fields.
     */
    void parseDF4(alt_format_df& df4);

    /*
     * Splits a CSV line into fields using the given delimiter.
     * Returns a vector of strings, one for each field.
     * This simple splitter does not handle quotes or escaped delimiters,
     * which is fine for the CSV exports we expect.
     */
    std::vector<std::string> splitLine(const std::string& line, char delimiter);

public:
    
    /*
     * Constructor: stores the paths to the four CSV files.
     */
    CSVParser(const std::string& df1_path,
              const std::string& df2_path,
              const std::string& df3_path,
              const std::string& df4_path);

    /*
     * Loads all four dataframes by calling the private parse methods in sequence.
     * After this call, the four structures will contain the data from the CSV files.
     */
    void loadAll(var_columns_df& df1,
                 alt_columns_df& df2,
                 sample_columns_df& df3,
                 alt_format_df& df4);
};

#endif // CSV_PARSER_H